# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: daily
      time: '12:00'
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: '12:00'
    groups:
      actions:
        patterns:
          - "*"
