name: marine_qc

channels:
    - conda-forge
    - nodefaults

dependencies:
    #marine_qc
    - python>=3.10,<3.14
    - xclim
    - cf_xarray
    - matplotlib

    #development
    - black =25.1.0
    - blackdoc =0.3.9
    - bump-my-version >=0.28.1
    - codespell=2.3.0
    - coverage >=7.5.0
    - coveralls >=4.0.1  # Note: coveralls is not yet compatible with Python 3.13
    - deptry =0.20.0
    - distributed >=2.0
    - flake8 >=7.1.1
    - flake8-rst-docstrings >=0.3.0
    - flit >=3.9.0
    - isort =5.13.2
    - notebook
    - pip >=24.2.0
    - pre-commit >=3.7
    - pylint >=3.3.1
    - pytest >=8.0.0
    - pytest-cov >=5.0.0
    - pytest-socket >=0.6.0
    - pytest-xdist >=3.2
    - ruff >=0.7.0
    - vulture =2.14

    #documentation
    - ipykernel
    - ipython >= 8.5.0
    - myst-nb >= 1.2.0
    - nbconvert >=7.16.4
    - numpydoc >=1.8.0
    - sphinx >=7.0.0
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - sphinx-book-theme >=1.0

    #from pypi
    - pip:
      - cdm_reader_mapper
      - pyproj
